export const GAME_STATE = {
  ON_SETUP: "ON_SETUP",
  ONGOING: "ONGOING",
  FINISHED: "FINISHED",
  MATCHING: "MATCHING",
}

export const GAME_TYPE = {
  STANDALONE: "STANDALONE",
  NETWORK: "NETWORK",
}

export default {
  GAME_RESTART: 'GAME_RESTART',
  SELECT_GAME_TYPE: 'SELECT_GAME_TYPE',
  SET_PLAYERS: 'SET_PLAYERS',
  SET_GAME_STATE: 'SET_GAME_STATE',
  SELECT_BOARD_SQUARE: 'SELECT_BOARD_SQUARE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  MAKE_PLAYER_MOVE: 'MAKE_PLAYER_MOVE',
}